#!/usr/bin/env node
/**
 * Signs every vector declared in vectors.src.mjs and writes:
 *   vectors/NV-XX-<slug>.json                 one file per vector, for review and for diffs
 *   web-bot-auth-negative-vectors.json        all of them in one file, for a test runner
 *
 * Per-vector files are the artifact and the combined file is derived from them, so the two cannot
 * disagree. Every signature is made with the Ed25519 key from RFC 9421 Appendix B.1.4, whose two
 * halves are printed in the RFC, so the whole set can be regenerated by anyone.
 *
 *   node generate.mjs           regenerate and write
 *   node generate.mjs --check   regenerate and fail on any drift, for CI
 */
import { sign as edSign, createPrivateKey, createPublicKey, verify as edVerify } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PRIVATE_PEM, PUBLIC_PEM, PUBLIC_JWK, KEY_ID } from './lib/rfc9421-b14.mjs';
import { VECTORS, GOOD_DIRECTORY, OMITTED } from './vectors.src.mjs';
import { NOTES } from './notes.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const VDIR = join(HERE, 'vectors');
const COMBINED = join(HERE, 'web-bot-auth-negative-vectors.json');
const CHECK = process.argv.includes('--check');

const privateKey = createPrivateKey(PRIVATE_PEM);
const publicKey = createPublicKey(PUBLIC_PEM);

/**
 * An RFC 9421 signature base, section 2.5: one line per covered component, then @signature-params.
 * Written out rather than taken from a library on purpose — a vector set whose bytes come from one
 * implementation's helper only proves that implementation agrees with itself.
 */
function buildBase(components, values, paramsValue) {
  const lines = components.map((id) => {
    const v = values[id];
    if (v === undefined) throw new Error(`no value for component ${id}`);
    return `${id}: ${v}`;
  });
  lines.push(`"@signature-params": ${paramsValue}`);
  return lines.join('\n');
}

const GROUPS = [
  { id: 'signature', title: 'The signature itself' },
  { id: 'signature-agent', title: 'The Signature-Agent header' },
];

const built = [];
for (const v of VECTORS) {
  const s = v.signature;
  const signedBase = buildBase(s.components, s.signedValues, s.paramsValue);
  const sig = edSign(null, Buffer.from(signedBase, 'utf8'), privateKey);

  // The invariant that makes a negative vector honest: the signature is CORRECT over the base the
  // signer built. Each vector must fail for the reason it names and for no other, so anything a
  // verifier could legitimately blame instead has to be right. Proven, not asserted.
  if (!edVerify(null, Buffer.from(signedBase, 'utf8'), publicKey, sig)) {
    throw new Error(`${v.id}: generated signature does not verify over its own base`);
  }

  // What a conformant verifier rebuilds from `request`. Equal to signedBase for every vector except
  // the ones where that difference IS the test. null where the request does not permit a base to be
  // built at all — a broken header, an unmatched label, an absent component.
  let expectedBase = null;
  if (s.expectedValues) {
    try { expectedBase = buildBase(s.components, s.expectedValues, s.paramsValue); } catch { expectedBase = null; }
  }

  const headers = {
    ...v.request.headers,
    'Signature-Input': `${s.label}=${s.paramsValue}`,
    Signature: `${s.renameSignatureMemberTo ?? s.label}=:${sig.toString('base64')}:`,
    ...(s.overrideHeaders ?? {}),
  };

  if (!['mechanical', 'verifier-must', 'discretionary'].includes(v.enforcement)) {
    throw new Error(`${v.id}: unknown enforcement "${v.enforcement}"`);
  }
  const note = NOTES[v.expected.reason];
  if (!note) throw new Error(`${v.id}: reason "${v.expected.reason}" has no entry in notes.mjs`);
  if (note.outcome !== v.expected.outcome) {
    throw new Error(`${v.id}: expected.outcome "${v.expected.outcome}" disagrees with notes.mjs ("${note.outcome}")`);
  }

  built.push({
    id: v.id,
    title: v.title,
    group: note.group,
    class: v.class,
    provenance: v.provenance,
    ...(v.observed ? { observed: v.observed } : {}),
    expected: v.expected,
    enforcement: v.enforcement,
    basis: v.basis,
    note: v.note,
    now: v.now,
    request: { ...v.request, headers },
    signature: {
      label: s.label,
      components: s.components,
      paramsValue: s.paramsValue,
      // What the signer put into the base it signed, and what a verifier must derive from `request`.
      // Equal for every vector except the ones where that difference IS the test.
      signedValues: s.signedValues,
      expectedValues: s.expectedValues,
      signedBase,
      expectedBase,
      baseDiffers: expectedBase !== signedBase,
    },
    key: { source: 'RFC 9421 Appendix B.1.4', keyid: KEY_ID, jwk: PUBLIC_JWK },
    // Supplied inline and keyed to the address the header actually names, so an adapter that looks
    // the directory up by URL finds it. null where the request names no address at all.
    directory: v.directoryFor
      ? { url: `${v.directoryFor.replace(/\/$/, '')}/.well-known/http-message-signatures-directory`, ...GOOD_DIRECTORY }
      : null,
    ...(v.directoryNote ? { directoryNote: v.directoryNote } : {}),
  });
}

const combined = {
  schema: 'web-bot-auth-negative-vectors-v1',
  document: 'draft-meunier-webbotauth-httpsig-protocol-02',
  issue: 'https://github.com/thibmeu/http-message-signatures-directory/issues/11',
  numberOfTests: built.length,
  key: { source: 'RFC 9421 Appendix B.1.4', keyid: KEY_ID, jwk: PUBLIC_JWK },
  header: [
    'Requests that must not verify, and the reason each failure should carry.',
    'expected.outcome is the draft\'s own (Appendix C.1, Verifier Outcomes) and is normative.',
    'expected.reason is a finer vocabulary this set proposes; notes explains each name.',
    'A verifier that wants none of the vocabulary can check expected.outcome alone and still',
    'have a complete conformance run against the text as it stands.',
    'enforcement says how binding the rejection is: mechanical (verification cannot succeed),',
    'verifier-must (the document tells the verifier what to do), or discretionary (the obligation',
    'is on the signer, or the document says MAY; the outcome is what a verifier that enforces gives).',
    'These vectors state what a verifier CONCLUDES. What it discloses on the wire is local policy',
    'and this set takes no position on it.',
  ],
  notes: NOTES,
  omitted: OMITTED,
  testGroups: GROUPS.map((g) => ({
    group: g.id,
    title: g.title,
    tests: built.filter((b) => b.group === g.id),
  })),
};

const ungrouped = built.filter((b) => !GROUPS.some((g) => g.id === b.group));
if (ungrouped.length) throw new Error(`vectors in no group: ${ungrouped.map((b) => b.id).join(', ')}`);
const inGroups = combined.testGroups.reduce((n, g) => n + g.tests.length, 0);
if (inGroups !== built.length) throw new Error(`grouping lost vectors: ${inGroups} of ${built.length}`);

let drift = 0;
const write = (path, text) => {
  let before = null;
  try { before = readFileSync(path, 'utf8'); } catch { /* new file */ }
  if (before === text) return false;
  drift++;
  if (!CHECK) writeFileSync(path, text);
  return true;
};

const wanted = new Set();
for (const b of built) {
  const slug = VECTORS.find((v) => v.id === b.id).slug;
  const name = `${b.id}-${slug}.json`;
  wanted.add(name);
  const changed = write(join(VDIR, name), JSON.stringify(b, null, 2) + '\n');
  console.log(`${changed ? (CHECK ? 'DRIFT' : 'wrote') : 'ok   '}  ${name}`);
}
for (const f of readdirSync(VDIR).filter((f) => f.endsWith('.json'))) {
  if (!wanted.has(f)) { drift++; if (!CHECK) unlinkSync(join(VDIR, f)); console.log(`${CHECK ? 'STALE' : 'removed'}  ${f}`); }
}
const cChanged = write(COMBINED, JSON.stringify(combined, null, 2) + '\n');
console.log(`${cChanged ? (CHECK ? 'DRIFT' : 'wrote') : 'ok   '}  web-bot-auth-negative-vectors.json  (${built.length} tests)`);

if (CHECK && drift) { console.error(`\n${drift} file(s) differ from what this key and source produce. Run: node generate.mjs`); process.exit(1); }
